package mod.yourmediocrepal.init;

import com.terraformersmc.terraform.boat.api.item.TerraformBoatItemHelper;
import com.terraformersmc.terraform.boat.impl.item.TerraformBoatItem;
import mod.yourmediocrepal.Noel;
import mod.yourmediocrepal.entity.NoelBoats;
import mod.yourmediocrepal.entity.NoelEntities;
import mod.yourmediocrepal.event.NoelEffects;
import mod.yourmediocrepal.item.ItemBellRinger;
import mod.yourmediocrepal.item.ItemHangingSign;
import mod.yourmediocrepal.item.ItemHotChocolate;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.component.type.FoodComponent;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.effect.StatusEffectInstance;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.item.*;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.RegistryKey;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class NoelItems {

    public static void initialize() {
        Registry.register(Registries.ITEM_GROUP, NOEL_ITEM_GROUP_KEY, NOEL_ITEM_GROUP);

        ItemGroupEvents.modifyEntriesEvent(NOEL_ITEM_GROUP_KEY).register(itemGroup -> {
            itemGroup.add(NoelItems.BELL_RINGER);
            itemGroup.add(NoelItems.CANDY_CANE);
            itemGroup.add(NoelItems.DISC_DECK_THE_HALLS);
            itemGroup.add(NoelItems.DISC_JINGLE_BELLS);
            itemGroup.add(NoelItems.DISC_OH_CHRISTMAS_TREE);
            itemGroup.add(NoelItems.DISC_SUGAR_PLUM_FAIRIES);
            itemGroup.add(NoelItems.DISC_UP_ON_A_HOUSETOP);
            itemGroup.add(NoelItems.DISC_WE_WISH_YOU);
            itemGroup.add(NoelItems.GELATIN);
            itemGroup.add(NoelItems.GINGER_BREAD_COOKIE);
            itemGroup.add(NoelItems.MUG);
            itemGroup.add(NoelItems.HOT_CHOCOLATE);
            itemGroup.add(NoelItems.MOLASSES);
            itemGroup.add(NoelItems.SPIRIT);
            itemGroup.add(NoelItems.SUGAR_PLUM);
            itemGroup.add(NoelItems.SANTA_BOOTS);
            itemGroup.add(NoelItems.SANTA_LEGGINGS);
            itemGroup.add(NoelItems.SANTA_CHESTPLATE);
            itemGroup.add(NoelItems.SANTA_HELMET);
            itemGroup.add(NoelItems.PEPPERMINT_CANDY);
            itemGroup.add(NoelItems.PEPPERMINT_BOOTS);
            itemGroup.add(NoelItems.PEPPERMINT_LEGGINGS);
            itemGroup.add(NoelItems.PEPPERMINT_CHESTPLATE);
            itemGroup.add(NoelItems.PEPPERMINT_HELMET);
            itemGroup.add(NoelItems.GINGER_BREAD_SPAWN_EGG);
            itemGroup.add(NoelItems.SANTA_SPAWN_EGG);
            itemGroup.add(NoelItems.SUGAR_PLUM_FAIRY_SPAWN_EGG);

            itemGroup.add(NoelBlocks.ADVENT_CALENDAR.asItem());
            itemGroup.add(NoelBlocks.GLOWSTONE_STAR.asItem());
            itemGroup.add(NoelBlocks.GOLD_STAR.asItem());
            itemGroup.add(NoelBlocks.KETTLE.asItem());
            itemGroup.add(NoelBlocks.PRESENT.asItem());
            itemGroup.add(NoelBlocks.PRESENT_TRAP.asItem());
            itemGroup.add(NoelBlocks.OAK_WREATH.asItem());
            itemGroup.add(NoelBlocks.SPRUCE_WREATH.asItem());
            itemGroup.add(NoelBlocks.BIRCH_WREATH.asItem());
            itemGroup.add(NoelBlocks.JUNGLE_WREATH.asItem());
            itemGroup.add(NoelBlocks.DARK_OAK_WREATH.asItem());
            itemGroup.add(NoelBlocks.ACACIA_WREATH.asItem());
            itemGroup.add(NoelBlocks.AZALEA_WREATH.asItem());
            itemGroup.add(NoelBlocks.MANGROVE_WREATH.asItem());
            itemGroup.add(NoelBlocks.CHERRY_WREATH.asItem());
            itemGroup.add(NoelBlocks.POINSETTIA.asItem());
            itemGroup.add(NoelBlocks.MISTLETOE.asItem());
            itemGroup.add(NoelBlocks.GINGER_BREAD_BLOCK.asItem());
            itemGroup.add(NoelBlocks.GINGER_BREAD_SLAB.asItem());
            itemGroup.add(NoelBlocks.GINGER_BREAD_STAIRS.asItem());
            itemGroup.add(NoelBlocks.GINGER_BREAD_DOOR.asItem());
            itemGroup.add(NoelBlocks.GINGER_BREAD_WALL.asItem());
            itemGroup.add(NoelItems.GINGER_BREAD_SIGN);
            itemGroup.add(NoelItems.GINGER_BREAD_HANGING_SIGN);
            itemGroup.add(NoelBlocks.FROSTED_LOG.asItem());
            itemGroup.add(NoelBlocks.FROSTED_WOOD.asItem());
            itemGroup.add(NoelBlocks.STRIPPED_FROSTED_LOG.asItem());
            itemGroup.add(NoelBlocks.STRIPPED_FROSTED_WOOD.asItem());
            itemGroup.add(NoelBlocks.FROSTED_PLANKS.asItem());
            itemGroup.add(NoelBlocks.FROSTED_SLAB.asItem());
            itemGroup.add(NoelBlocks.FROSTED_STAIRS.asItem());
            itemGroup.add(NoelBlocks.FROSTED_TRAPDOOR.asItem());
            itemGroup.add(NoelBlocks.FROSTED_DOOR.asItem());
            itemGroup.add(NoelBlocks.FROSTED_FENCE.asItem());
            itemGroup.add(NoelBlocks.FROSTED_FENCE_GATE.asItem());
            itemGroup.add(NoelBlocks.FROSTED_BUTTON.asItem());
            itemGroup.add(NoelBlocks.FROSTED_PRESSURE_PLATE.asItem());
            itemGroup.add(NoelItems.FROSTED_SIGN);
            itemGroup.add(NoelItems.FROSTED_HANGING_SIGN);
            itemGroup.add(NoelItems.FROSTED_BOAT);
            itemGroup.add(NoelItems.FROSTED_CHEST_BOAT);
            itemGroup.add(NoelBlocks.PEPPERMINT_LOG.asItem());
            itemGroup.add(NoelBlocks.PEPPERMINT_PLANKS.asItem());
            itemGroup.add(NoelBlocks.PEPPERMINT_SLAB.asItem());
            itemGroup.add(NoelBlocks.PEPPERMINT_STAIRS.asItem());
            itemGroup.add(NoelBlocks.PEPPERMINT_TRAPDOOR.asItem());
            itemGroup.add(NoelBlocks.PEPPERMINT_DOOR.asItem());
            itemGroup.add(NoelBlocks.PEPPERMINT_FENCE.asItem());
            itemGroup.add(NoelBlocks.PEPPERMINT_FENCE_GATE.asItem());
            itemGroup.add(NoelBlocks.PEPPERMINT_BUTTON.asItem());
            itemGroup.add(NoelBlocks.PEPPERMINT_PRESSURE_PLATE.asItem());
            itemGroup.add(NoelBlocks.PEPPERMINT_WALL.asItem());
            itemGroup.add(NoelItems.PEPPERMINT_SIGN);
            itemGroup.add(NoelItems.PEPPERMINT_HANGING_SIGN);
            itemGroup.add(NoelBlocks.RED_GUMDROP.asItem());
            itemGroup.add(NoelBlocks.ORANGE_GUMDROP.asItem());
            itemGroup.add(NoelBlocks.YELLOW_GUMDROP.asItem());
            itemGroup.add(NoelBlocks.GREEN_GUMDROP.asItem());
            itemGroup.add(NoelBlocks.BLUE_GUMDROP.asItem());
            itemGroup.add(NoelBlocks.PURPLE_GUMDROP.asItem());
            itemGroup.add(NoelBlocks.BLACK_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.BLUE_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.BROWN_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.CYAN_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.GRAY_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.GREEN_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.LIGHT_BLUE_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.LIME_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.MAGENTA_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.ORANGE_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.PINK_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.PURPLE_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.RED_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.LIGHT_GRAY_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.WHITE_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.YELLOW_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.DIAMOND_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.EMERALD_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.GLASS_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.GOLD_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.IRON_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.COPPER_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.EXPOSED_COPPER_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.WEATHERED_COPPER_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.OXIDIZED_COPPER_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.WAXED_COPPER_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.WAXED_EXPOSED_COPPER_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.WAXED_WEATHERED_COPPER_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.WAXED_OXIDIZED_COPPER_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.REDSTONE_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.LAPIS_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.COAL_ORNAMENT.asItem());
            itemGroup.add(NoelBlocks.BLACK_STOCKING.asItem());
            itemGroup.add(NoelBlocks.BLUE_STOCKING.asItem());
            itemGroup.add(NoelBlocks.BROWN_STOCKING.asItem());
            itemGroup.add(NoelBlocks.CYAN_STOCKING.asItem());
            itemGroup.add(NoelBlocks.GRAY_STOCKING.asItem());
            itemGroup.add(NoelBlocks.GREEN_STOCKING.asItem());
            itemGroup.add(NoelBlocks.LIGHT_BLUE_STOCKING.asItem());
            itemGroup.add(NoelBlocks.LIME_STOCKING.asItem());
            itemGroup.add(NoelBlocks.MAGENTA_STOCKING.asItem());
            itemGroup.add(NoelBlocks.ORANGE_STOCKING.asItem());
            itemGroup.add(NoelBlocks.PINK_STOCKING.asItem());
            itemGroup.add(NoelBlocks.PURPLE_STOCKING.asItem());
            itemGroup.add(NoelBlocks.RED_STOCKING.asItem());
            itemGroup.add(NoelBlocks.LIGHT_GRAY_STOCKING.asItem());
            itemGroup.add(NoelBlocks.WHITE_STOCKING.asItem());
            itemGroup.add(NoelBlocks.YELLOW_STOCKING.asItem());
            itemGroup.add(NoelBlocks.BLACK_RIBBON.asItem());
            itemGroup.add(NoelBlocks.BLUE_RIBBON.asItem());
            itemGroup.add(NoelBlocks.BROWN_RIBBON.asItem());
            itemGroup.add(NoelBlocks.CYAN_RIBBON.asItem());
            itemGroup.add(NoelBlocks.GRAY_RIBBON.asItem());
            itemGroup.add(NoelBlocks.GREEN_RIBBON.asItem());
            itemGroup.add(NoelBlocks.LIGHT_BLUE_RIBBON.asItem());
            itemGroup.add(NoelBlocks.LIGHT_GRAY_RIBBON.asItem());
            itemGroup.add(NoelBlocks.LIME_RIBBON.asItem());
            itemGroup.add(NoelBlocks.MAGENTA_RIBBON.asItem());
            itemGroup.add(NoelBlocks.ORANGE_RIBBON.asItem());
            itemGroup.add(NoelBlocks.PINK_RIBBON.asItem());
            itemGroup.add(NoelBlocks.PURPLE_RIBBON.asItem());
            itemGroup.add(NoelBlocks.RED_RIBBON.asItem());
            itemGroup.add(NoelBlocks.WHITE_RIBBON.asItem());
            itemGroup.add(NoelBlocks.YELLOW_RIBBON.asItem());

        });
    }
    public static Item register(Item item, String id) {
        Identifier itemID = Identifier.of(Noel.MOD_ID, id);
        Item registeredItem = Registry.register(Registries.ITEM, itemID, item);

        return registeredItem;
    }

    public static final Item BELL_RINGER = register(new ItemBellRinger(new Item.Settings().maxCount(1)), "bell_ringer");
    public static final Item CANDY_CANE = register(new Item(new Item.Settings().food(new FoodComponent.Builder().snack().nutrition(1).build())), "candy_cane");
    public static final Item DISC_DECK_THE_HALLS = register(new Item(new Item.Settings().jukeboxPlayable(NoelSounds.DISC_DECK_THE_HALLS_KEY).maxCount(1)), "disc_deck_the_halls");
    public static final Item DISC_JINGLE_BELLS = register(new Item(new Item.Settings().jukeboxPlayable(NoelSounds.DISC_JINGLE_BELLS_KEY).maxCount(1)), "disc_jingle_bells");
    public static final Item DISC_OH_CHRISTMAS_TREE = register(new Item(new Item.Settings().jukeboxPlayable(NoelSounds.DISC_OH_CHRISTMAS_TREE_KEY).maxCount(1)), "disc_oh_christmas_tree");
    public static final Item DISC_SUGAR_PLUM_FAIRIES = register(new Item(new Item.Settings().jukeboxPlayable(NoelSounds.DISC_SUGAR_PLUM_FAIRIES_KEY).maxCount(1)), "disc_sugar_plum_fairies");
    public static final Item DISC_UP_ON_A_HOUSETOP = register(new Item(new Item.Settings().jukeboxPlayable(NoelSounds.DISC_UP_ON_A_HOUSETOP_KEY).maxCount(1)), "disc_up_on_a_housetop");
    public static final Item DISC_WE_WISH_YOU = register(new Item(new Item.Settings().jukeboxPlayable(NoelSounds.DISC_WE_WISH_YOU_KEY).maxCount(1)), "disc_we_wish_you");
    public static final Item FROSTED_SIGN = register(new ItemHangingSign(NoelBlocks.FROSTED_STANDING_SIGN, NoelBlocks.FROSTED_WALL_SIGN, new Item.Settings()), "frosted_sign");
    public static final Item FROSTED_HANGING_SIGN = register(new ItemHangingSign(NoelBlocks.FROSTED_HANGING_SIGN, NoelBlocks.FROSTED_WALL_HANGING_SIGN, new Item.Settings()), "frosted_hanging_sign");
    public static final Item GELATIN = register(new Item(new Item.Settings()), "gelatin");
    public static final Item FROSTED_BOAT = TerraformBoatItemHelper.registerBoatItem(NoelBoats.FROSTED_BOAT_ID, NoelBoats.FROSTED_BOAT_KEY, false);
    public static final Item FROSTED_CHEST_BOAT = TerraformBoatItemHelper.registerBoatItem(NoelBoats.FROSTED_CHEST_BOAT_ID, NoelBoats.FROSTED_BOAT_KEY, true);
    public static final Item GINGER_BREAD_COOKIE = register(new Item(new Item.Settings().food(new FoodComponent.Builder().snack().nutrition(1).build())), "ginger_bread_cookie");
    public static final Item GINGER_BREAD_SIGN = register(new ItemHangingSign(NoelBlocks.GINGER_BREAD_STANDING_SIGN, NoelBlocks.GINGER_BREAD_WALL_SIGN, new Item.Settings()), "ginger_bread_sign");
    public static final Item GINGER_BREAD_HANGING_SIGN = register(new ItemHangingSign(NoelBlocks.GINGER_BREAD_HANGING_SIGN, NoelBlocks.GINGER_BREAD_WALL_HANGING_SIGN, new Item.Settings()), "ginger_bread_hanging_sign");
    public static final Item HOT_CHOCOLATE = register(new ItemHotChocolate(new Item.Settings().food(new FoodComponent.Builder().nutrition(1).statusEffect(new StatusEffectInstance(NoelEffects.FESTIVE, 6000, 0), 1).alwaysEdible().build()).maxCount(1)), "hot_chocolate");
    public static final Item MOLASSES = register(new Item(new Item.Settings()), "molasses");
    public static final Item MUG = register(new Item(new Item.Settings().maxCount(16)), "mug");
    public static final Item MUG_MILK = register(new Item(new Item.Settings()), "mug_milk");
    public static final Item SPIRIT = register(new Item(new Item.Settings()), "spirit");
    public static final Item SUGAR_PLUM = register(new Item(new Item.Settings().food(new FoodComponent.Builder().snack().nutrition(1).build())), "sugar_plum");
    public static final Item PEPPERMINT_CANDY = register(new Item(new Item.Settings().food(new FoodComponent.Builder().snack().nutrition(1).build())), "peppermint_candy");
    public static final Item PEPPERMINT_SIGN = register(new ItemHangingSign(NoelBlocks.PEPPERMINT_STANDING_SIGN, NoelBlocks.PEPPERMINT_WALL_SIGN, new Item.Settings()), "peppermint_sign");
    public static final Item PEPPERMINT_HANGING_SIGN = register(new ItemHangingSign(NoelBlocks.PEPPERMINT_HANGING_SIGN, NoelBlocks.PEPPERMINT_WALL_HANGING_SIGN, new Item.Settings()), "peppermint_hanging_sign");

    public static final Item WARM_MILK = register(new Item(new Item.Settings()), "warm_milk");


    public static final Item PEPPERMINT_HELMET = register(new ArmorItem(NoelArmorMaterials.PEPPERMINT, ArmorItem.Type.HELMET, new Item.Settings().maxDamage(ArmorItem.Type.HELMET.getMaxDamage(NoelArmorMaterials.PEPPERMINT_DURABILITY_MULTIPLIER))), "peppermint_helmet");
    public static final Item PEPPERMINT_CHESTPLATE = register(new ArmorItem(NoelArmorMaterials.PEPPERMINT, ArmorItem.Type.CHESTPLATE, new Item.Settings().maxDamage(ArmorItem.Type.CHESTPLATE.getMaxDamage(NoelArmorMaterials.PEPPERMINT_DURABILITY_MULTIPLIER))), "peppermint_chestplate");
    public static final Item PEPPERMINT_LEGGINGS = register(new ArmorItem(NoelArmorMaterials.PEPPERMINT, ArmorItem.Type.LEGGINGS, new Item.Settings().maxDamage(ArmorItem.Type.LEGGINGS.getMaxDamage(NoelArmorMaterials.PEPPERMINT_DURABILITY_MULTIPLIER))), "peppermint_leggings");
    public static final Item PEPPERMINT_BOOTS = register(new ArmorItem(NoelArmorMaterials.PEPPERMINT, ArmorItem.Type.BOOTS, new Item.Settings().maxDamage(ArmorItem.Type.BOOTS.getMaxDamage(NoelArmorMaterials.PEPPERMINT_DURABILITY_MULTIPLIER))), "peppermint_boots");
    public static final Item SANTA_HELMET = register(new ArmorItem(NoelArmorMaterials.SANTA, ArmorItem.Type.HELMET, new Item.Settings().maxDamage(ArmorItem.Type.HELMET.getMaxDamage(NoelArmorMaterials.SANTA_DURABILITY_MULTIPLIER))), "santa_helmet");
    public static final Item SANTA_CHESTPLATE = register(new ArmorItem(NoelArmorMaterials.SANTA, ArmorItem.Type.CHESTPLATE, new Item.Settings().maxDamage(ArmorItem.Type.CHESTPLATE.getMaxDamage(NoelArmorMaterials.SANTA_DURABILITY_MULTIPLIER))), "santa_chestplate");
    public static final Item SANTA_LEGGINGS = register(new ArmorItem(NoelArmorMaterials.SANTA, ArmorItem.Type.LEGGINGS, new Item.Settings().maxDamage(ArmorItem.Type.LEGGINGS.getMaxDamage(NoelArmorMaterials.SANTA_DURABILITY_MULTIPLIER))), "santa_leggings");
    public static final Item SANTA_BOOTS = register(new ArmorItem(NoelArmorMaterials.SANTA, ArmorItem.Type.BOOTS, new Item.Settings().maxDamage(ArmorItem.Type.BOOTS.getMaxDamage(NoelArmorMaterials.SANTA_DURABILITY_MULTIPLIER))), "santa_boots");

    public static final Item GINGER_BREAD_SPAWN_EGG = register(new SpawnEggItem(NoelEntities.GINGER_BREAD, 0xCE7E00, 0xFFFFFF, new Item.Settings()), "ginger_bread_spawn_egg");
    public static final Item SANTA_SPAWN_EGG = register(new SpawnEggItem(NoelEntities.SANTA, 0xCC0000, 0xFFFFFF, new Item.Settings()), "santa_spawn_egg");
    public static final Item SUGAR_PLUM_FAIRY_SPAWN_EGG = register(new SpawnEggItem(NoelEntities.SUGAR_PLUM_FAIRY, 0xB4A7D6, 0xEAD1DC, new Item.Settings()), "sugar_plum_fairy_spawn_egg");


    public static final RegistryKey<ItemGroup> NOEL_ITEM_GROUP_KEY = RegistryKey.of(Registries.ITEM_GROUP.getKey(), Identifier.of(Noel.MOD_ID, "item_group"));
    public static final ItemGroup NOEL_ITEM_GROUP = FabricItemGroup.builder().icon(() -> new ItemStack(NoelItems.CANDY_CANE)).displayName(Text.translatable("itemGroup.noel")).build();

}
